twig:
    default_path: '%kernel.project_dir%/templates'
    paths:
        "%kernel.project_dir%/public": public_path
    form_themes: ['form/bulma.html.twig']


when@test:
    twig:
        strict_variables: true
